#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RELEASE_INFO_PATH="${ROOT_DIR}/release_info.json"
APP_VERSION_PATH="${ROOT_DIR}/src/app_version.py"
SETUP_ISS_PATH="${ROOT_DIR}/installer/setup.iss"
RELEASE_NOTES_PATH="${ROOT_DIR}/RELEASE_NOTES.md"

if [[ ! -f "${RELEASE_INFO_PATH}" ]]; then
    echo "[X] release_info.json not found: ${RELEASE_INFO_PATH}" >&2
    exit 1
fi

python3 - <<'PY' "$RELEASE_INFO_PATH" "$APP_VERSION_PATH" "$SETUP_ISS_PATH" "$RELEASE_NOTES_PATH"
import json
import re
import sys
from datetime import date
from pathlib import Path

release_info_path = Path(sys.argv[1])
app_version_path = Path(sys.argv[2])
setup_iss_path = Path(sys.argv[3])
release_notes_path = Path(sys.argv[4])

with release_info_path.open('r', encoding='utf-8') as fh:
    release = json.load(fh)

app_name = str(release.get('app_name', '')).strip()
version = str(release.get('version', '')).strip()
publisher = str(release.get('publisher', '')).strip()

if not app_name or not version or not publisher:
    print('[X] release_info.json must contain app_name, version, and publisher.', file=sys.stderr)
    sys.exit(1)

if not re.match(r'^[0-9]+\.[0-9]+\.[0-9]+([-.+][0-9A-Za-z.-]+)?$', version):
    print(f'[X] Invalid version format: {version}', file=sys.stderr)
    print('    Use semver style, e.g. 1.2.3 or 1.2.3-beta.1', file=sys.stderr)
    sys.exit(1)

patch_notes = []
for item in release.get('patch_notes', []) or []:
    text = str(item).strip()
    if text:
        patch_notes.append(text)

if not patch_notes:
    patch_notes = ['No patch notes provided.']

note_lines = []
for note in patch_notes:
    escaped = note.replace('"', '\\"')
    note_lines.append(f'    "{escaped}",')

app_version_lines = [
    '"""Generated by scripts/shell/sync_release.sh. Do not edit manually."""',
    '',
    f'APP_NAME = "{app_name}"',
    f'APP_VERSION = "{version}"',
    f'APP_PUBLISHER = "{publisher}"',
    '',
    'APP_PATCH_NOTES = [',
    *note_lines,
    ']',
    '',
]
app_version_path.write_text('\n'.join(app_version_lines), encoding='utf-8')

if not setup_iss_path.exists():
    print(f'[X] setup.iss not found: {setup_iss_path}', file=sys.stderr)
    sys.exit(1)

iss_text = setup_iss_path.read_text(encoding='utf-8')
iss_text = re.sub(r'(?m)^#define\s+MyAppName\s+"[^"]+"', f'#define MyAppName      "{app_name}"', iss_text)
iss_text = re.sub(r'(?m)^#define\s+MyAppVersion\s+"[^"]+"', f'#define MyAppVersion   "{version}"', iss_text)
iss_text = re.sub(r'(?m)^#define\s+MyAppPublisher\s+"[^"]+"', f'#define MyAppPublisher "{publisher}"', iss_text)
setup_iss_path.write_text(iss_text, encoding='utf-8')

today = date.today().strftime('%Y-%m-%d')
entry_lines = [f'## {version} ({today})', '']
entry_lines.extend(f'- {note}' for note in patch_notes)
entry_lines.append('')
entry_text = '\n'.join(entry_lines)

notes_header = f'# {app_name} Release Notes'
notes_body = release_notes_path.read_text(encoding='utf-8') if release_notes_path.exists() else ''

if not notes_body.strip():
    notes_body = f'{notes_header}\n\n'
elif not re.search(r'(?m)^#\s+.+\s+Release Notes\s*$', notes_body):
    notes_body = f'{notes_header}\n\n{notes_body}'

version_section_pattern = rf'(?ms)^##\s+{re.escape(version)}\s+\([^)]+\)\n.*?(?=^##\s+|\Z)'
if re.search(version_section_pattern, notes_body):
    notes_body = re.sub(version_section_pattern, entry_text, notes_body)
else:
    trimmed = notes_body.rstrip()
    if trimmed:
        notes_body = f'{trimmed}\n\n{entry_text}'
    else:
        notes_body = f'{notes_header}\n\n{entry_text}'

release_notes_path.write_text(notes_body, encoding='utf-8')
PY

echo "[OK] Release metadata synced."
echo "     Source: ${RELEASE_INFO_PATH}"
echo "     Updated: src/app_version.py, installer/setup.iss, RELEASE_NOTES.md"
