"""Generated by scripts/sync_release.ps1. Do not edit manually."""

APP_NAME = "Outpost"
APP_VERSION = "1.0.0"
APP_PUBLISHER = "Megamu Utilities"

APP_PATCH_NOTES = [
    "Initial Outpost monitor scaffold.",
]
