#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Syncs release metadata from one file to version artifact(s).

.DESCRIPTION
    Source of truth: release_info.json (project root)
    Targets updated by this script:
      - src/app_version.py
      - RELEASE_NOTES.md
#>

$ErrorActionPreference = 'Stop'

$ProjectRoot = Split-Path -Parent $PSScriptRoot
$ReleaseInfoPath = Join-Path $ProjectRoot 'release_info.json'
$AppVersionPath = Join-Path $ProjectRoot 'src\app_version.py'
$ReleaseNotesPath = Join-Path $ProjectRoot 'RELEASE_NOTES.md'

if (-not (Test-Path $ReleaseInfoPath)) {
    Write-Host "[X] release_info.json not found: $ReleaseInfoPath" -ForegroundColor Red
    exit 1
}

$release = Get-Content -Raw -Path $ReleaseInfoPath | ConvertFrom-Json

if (-not $release.app_name -or -not $release.version -or -not $release.publisher) {
    Write-Host '[X] release_info.json must contain app_name, version, and publisher.' -ForegroundColor Red
    exit 1
}

$appName = [string]$release.app_name
$version = [string]$release.version
$publisher = [string]$release.publisher

if ($version -notmatch '^[0-9]+\.[0-9]+\.[0-9]+([-.+][0-9A-Za-z.-]+)?$') {
    Write-Host "[X] Invalid version format: $version" -ForegroundColor Red
    Write-Host '    Use semver style, e.g. 1.2.3 or 1.2.3-beta.1' -ForegroundColor Cyan
    exit 1
}

$patchNotes = @()
if ($release.patch_notes) {
    foreach ($item in $release.patch_notes) {
        $text = [string]$item
        if (-not [string]::IsNullOrWhiteSpace($text)) {
            $patchNotes += $text.Trim()
        }
    }
}

$noteLines = @()
foreach ($note in $patchNotes) {
    $escaped = $note.Replace("'", "\\'")
    $noteLines += ("    '" + $escaped + "',")
}
if ($noteLines.Count -eq 0) {
    $noteLines += "    'No patch notes provided.',"
}

$appVersionLines = @(
    '# Generated by scripts/sync_release.ps1. Do not edit manually.',
    ('APP_NAME = ' + "'" + $appName + "'"),
    ('APP_VERSION = ' + "'" + $version + "'"),
    ('APP_PUBLISHER = ' + "'" + $publisher + "'"),
    '',
    'APP_PATCH_NOTES = ['
) + $noteLines + @(
    ']',
    ''
)

$appVersionContent = $appVersionLines -join "`r`n"
Set-Content -Path $AppVersionPath -Value $appVersionContent -Encoding UTF8

$today = Get-Date -Format 'yyyy-MM-dd'
$entryLines = @(
    "## $version ($today)",
    ''
)
if ($patchNotes.Count -gt 0) {
    $entryLines += ($patchNotes | ForEach-Object { "- $_" })
}
else {
    $entryLines += '- No patch notes provided.'
}
$entryLines += ''
$entryText = $entryLines -join "`r`n"

$notesHeader = "# $appName Release Notes"
$notesBody = ''

if (Test-Path $ReleaseNotesPath) {
    $notesBody = Get-Content -Raw -Path $ReleaseNotesPath
}

if ([string]::IsNullOrWhiteSpace($notesBody)) {
    $notesBody = "$notesHeader`r`n`r`n"
}
elseif ($notesBody -notmatch '(?m)^#\s+.+\s+Release Notes\s*$') {
    $notesBody = "$notesHeader`r`n`r`n$notesBody"
}

# Idempotent behavior: update the existing section for this version instead of duplicating it.
$versionSectionPattern = "(?ms)^##\s+" + [regex]::Escape($version) + "\s+\([^)]+\)\r?\n.*?(?=^##\s+|\z)"
if ($notesBody -match $versionSectionPattern) {
    $notesBody = [regex]::Replace($notesBody, $versionSectionPattern, $entryText)
}
else {
    $trimmed = $notesBody.TrimEnd()
    if ($trimmed.Length -gt 0) {
        $notesBody = "$trimmed`r`n`r`n$entryText"
    }
    else {
        $notesBody = "$notesHeader`r`n`r`n$entryText"
    }
}

Set-Content -Path $ReleaseNotesPath -Value $notesBody -Encoding UTF8

Write-Host '[OK] Release metadata synced.' -ForegroundColor Green
Write-Host "     Source: $ReleaseInfoPath" -ForegroundColor DarkGray
Write-Host '     Updated: src/app_version.py, RELEASE_NOTES.md' -ForegroundColor DarkGray
