"""Generated by scripts/sync_release.ps1. Do not edit manually."""

APP_NAME = "Guardtower"
APP_VERSION = "1.1.2"
APP_PUBLISHER = "Megamu Utilities"

APP_PATCH_NOTES = [
    "Aadd registered machines table and delete functionality to dashboard.",
]

