"""Generated by scripts/sync_release.ps1. Do not edit manually."""

APP_NAME = "Guardtower"
APP_VERSION = "1.0.1"
APP_PUBLISHER = "Megamu Utilities"

APP_PATCH_NOTES = [
    "feat: Update version to 1.0.1 and enhance error handling with user info dialogs in main.py",
]

