# Generated by scripts/sync_release.ps1. Do not edit manually.
APP_NAME = 'Siegetower'
APP_VERSION = '1.0.0'
APP_PUBLISHER = 'MegamuUtilities'

APP_PATCH_NOTES = [
    'Initial release metadata scaffold.',
]

