# Generated by scripts/sync_release.ps1. Do not edit manually.
APP_NAME = 'Spotify'
APP_VERSION = '1.1.0'
APP_PUBLISHER = 'Spotify'

APP_PATCH_NOTES = [
    'Update version to 1.1.0 and add Windows tray support for macro management.',
]

