# Generated by scripts/sync_release.ps1. Do not edit manually.
APP_NAME = 'Siegetower'
APP_VERSION = '1.0.3'
APP_PUBLISHER = 'MegamuUtilities'

APP_PATCH_NOTES = [
    'Add functionality to check if a repeat macro is running and improve macro execution handling.',
]

