"""Generated by scripts/sync_release.ps1. Do not edit manually."""

APP_NAME = "Watchtower"
APP_VERSION = "1.1.10"
APP_PUBLISHER = "Megamu Utilities"

APP_PATCH_NOTES = [
    "Add ghost close delay configuration in MonitorUI and process tower.",
]

