"""Generated by scripts/sync_release.ps1. Do not edit manually."""

APP_NAME = "Watchtower"
APP_VERSION = "1.0.2"
APP_PUBLISHER = "Megamu Utilities"

APP_PATCH_NOTES = [
    "feat: Enhance action controller and monitor UI with text input support and escape route management",
    "Added support for typing text in the action controller, allowing for text actions in escape routes.",
    "Implemented loading and saving of escape routes from a JSON configuration file.",
    "Introduced a UI for selecting and editing escape routes, including options to create, delete, and modify routes.",
    "Enhanced the player monitor with adaptive color calibration features for improved detection accuracy.",
    "Updated the escape route editor to accommodate text actions alongside clicks and key presses.",
    "Added a new JSON configuration file for predefined escape routes.",
]

