"""Generated by scripts/sync_release.ps1. Do not edit manually."""

APP_NAME = "Watchtower"
APP_VERSION = "1.1.1"
APP_PUBLISHER = "Megamu Utilities"

APP_PATCH_NOTES = [
    "Update scan address handling and add default addresses for Process Tower.",
]

